title:
logo: /assets/img/logo.png
description: Resources for Microsoft Security, Compliance & Identity Management
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
social: linkedin/in/rtrigueiro
